# Generated by Django 5.2 on 2025-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название метки"
            ),
        ),
    ]
