# Generated by Django 5.2 on 2025-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Creation date"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Name"
            ),
        ),
    ]
